downloaded cypress along with first tests in new branch to align hist…
OSU-CS362-W24/final-project-362finalproj pull request #4
Opened 2024-03-14 17:45 UTC by vl538

…ories with main branch

2024-03-17 04:18 UTC, sorensri commented on cypress/e2e/src.cy.js
> +    cy.url().should('eq', 'http://localhost:8080/line.html')
Use baseUrl here '/line.html'

2024-03-17 04:21 UTC, sorensri commented on cypress/e2e/src.cy.js
> +describe('Correctly generates line chart', () => {
Remove these outer describe portions and shift-tab everything down. Replace 'passes' with the description

2024-03-17 04:23 UTC, sorensri requested changes
It looks good, just need two changes with the src.cy.js file

2024-03-17 23:48 UTC, vl538 commented
fixed the issue in new pull request

2024-03-18 01:18 UTC, sorensri approved these changes
Looks good

2024-03-18 01:45 UTC, merged